language: python

services:
  - postgresql

python:
  - "3.7"

install:
  - pip install -r test_requirements.txt
  - pip install codecov

before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - psql -c "CREATE USER briefme WITH PASSWORD 'briefme';" -U postgres
  - psql -c "ALTER USER briefme CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO briefme;" -U postgres
  - cp config/database.travis.yml config/database.yml

script:
  - pytest --cov=briefme_invoices tests

after_success:
  - codecov
