# Generated by Django 3.2.14 on 2022-08-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('briefme_invoices', '0003_statement_to_transaction_20201130_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='raw_statement',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='raw_transaction',
            field=models.JSONField(null=True),
        ),
    ]
